#!/bin/sh

caxx 4004.axx 4004.s -b b0
caxx z80.axx z80.s -b b1
caxx 6502.axx 6502.s -b b2
caxx 6800.axx 6800.s -b b3
caxx 6809.axx 6809.s -b b4
caxx 8080.axx 8080.s -b b5
caxx 8048.axx 8048.s -b b6
caxx 8051.axx 8051.s -b b7
caxx 68000.axx 68000.s -b b8
caxx vliw.axx vliw.s -b b9
caxx itanium.axx vliw.s -b b10
caxx x86_64.axx hello.s -b b11
caxx x86_64m.axx hello.s -b b12

paxx 4004.axx 4004.s -b a0
paxx z80.axx z80.s -b a1
paxx 6502.axx 6502.s -b a2
paxx 6800.axx 6800.s -b a3
paxx 6809.axx 6809.s -b a4
paxx 8080.axx 8080.s -b a5
paxx 8048.axx 8048.s -b a6
paxx 8051.axx 8051.s -b a7
paxx 68000.axx 68000.s -b a8
paxx vliw.axx vliw.s -b a9
paxx itanium.axx vliw.s -b a10
paxx x86_64.axx hello.s -b a11
paxx x86_64m.axx hello.s -b a12

cmp -s a0 b0
cmp -s a1 b1
cmp -s a2 b2
cmp -s a3 b3
cmp -s a4 b4
cmp -s a5 b5
cmp -s a6 b6
cmp -s a7 b7
cmp -s a8 b8
cmp -s a9 b9
cmp -s a10 b10
cmp -s a11 b11
cmp -s a12 b12

