#!/bin/sh

caxx 4004.axx 4004.s -b b0
caxx z80.axx z80.s -b b1
caxx 6502.axx 6502.s -b b2
caxx 6800.axx 6800.s -b b3
caxx 6809.axx 6809.s -b b4
caxx 8080.axx 8080.s -b b5
caxx 8048.axx 8048.s -b b6
caxx 8051.axx 8051.s -b b7
caxx 68000.axx 68000.s -b b8
caxx vliw.axx vliw.s -b b9
caxx itanium.axx vliw.s -b b10
caxx x86_64.axx hello.s -b b11
caxx x86_64m.axx hello.s -b b12
caxx aarch64_logical_mini.axx aarch64_logical_mini_demo.s -b b13
caxx bf.axx bf.s -b b14
caxx arrindex.axx arrindex.s -b b15
caxx passthru.axx passthru.s -b b16
caxx textmode.axx textmode.s -b b17
caxx 8080toz80.axx hello8080.s -b b18
caxx textmode.axx textmode.s -V > b19
caxx 8080toz80.axx hello8080.s -V > b20
caxx aarch64.axx aarch64.s -b b21

paxx 4004.axx 4004.s -b a0
paxx z80.axx z80.s -b a1
paxx 6502.axx 6502.s -b a2
paxx 6800.axx 6800.s -b a3
paxx 6809.axx 6809.s -b a4
paxx 8080.axx 8080.s -b a5
paxx 8048.axx 8048.s -b a6
paxx 8051.axx 8051.s -b a7
paxx 68000.axx 68000.s -b a8
paxx vliw.axx vliw.s -b a9
paxx itanium.axx vliw.s -b a10
paxx x86_64.axx hello.s -b a11
paxx x86_64m.axx hello.s -b a12
paxx aarch64_logical_mini.axx aarch64_logical_mini_demo.s -b a13
paxx bf.axx bf.s -b a14
paxx arrindex.axx arrindex.s -b a15
paxx passthru.axx passthru.s -b a16
paxx textmode.axx textmode.s -b a17
paxx 8080toz80.axx hello8080.s -b a18
paxx textmode.axx textmode.s -V > a19
paxx 8080toz80.axx hello8080.s -V > a20
paxx aarch64.axx aarch64.s -b a21

FAIL=0

cmp a0 b0 || FAIL=1
cmp a1 b1 || FAIL=1
cmp a2 b2 || FAIL=1
cmp a3 b3 || FAIL=1
cmp a4 b4 || FAIL=1
cmp a5 b5 || FAIL=1
cmp a6 b6 || FAIL=1
cmp a7 b7 || FAIL=1
cmp a8 b8 || FAIL=1
cmp a9 b9 || FAIL=1
cmp a10 b10 || FAIL=1
cmp a11 b11 || FAIL=1
cmp a12 b12 || FAIL=1
cmp a13 b13 || FAIL=1
cmp a14 b14 || FAIL=1
cmp a15 b15 || FAIL=1
cmp a16 b16 || FAIL=1
cmp a17 b17 || FAIL=1
cmp a18 b18 || FAIL=1
cmp a19 b19 || FAIL=1
cmp a20 b20 || FAIL=1
cmp a21 b21 || FAIL=1

if [ $FAIL -eq 0 ]; then
    echo "test all passed"
fi
